/** @format */

const swaggerAutogen = require("swagger-autogen")({ openapi: "3.0.0" });
const path = require("path");
console.log(process.env.PORT, "PORT__CONFIG")
const PORT = process.env.PORT || 5000;
const swaggerGen = () => {
	const doc = {
		info: {
			version: "3.0.0",
			title: "Users CRUD",
			description: "Documentation automatically generated by the <b>swagger-autogen</b> module.",
		},
		host: `localhost:${PORT}`,
		basePath: "/",
		schemes: ["http", "https"],
		consumes: ["application/json"],
		produces: ["application/json"],
		tags: [
			{
				name: "Users",
				description: "Endpoints",
			},
		],
		components: {
			securitySchemes: {
				bearerAuth: {
					type: "http",
					scheme: "bearer",
				},
			},
		},
	};

	const outputFile = "./src/output/swagger-output.json";
	const endpointsFiles = [path.join(__dirname, "../../app.js")];

	swaggerAutogen(outputFile, endpointsFiles, doc).then(async () => {
		await require(path.join(__dirname, "../../app.js"));
	});
};

module.exports = swaggerGen;
